### ISSUE TITLE
seems to swallow child updates

### ISSUE THREAD

**Issue by braco** [ollija/react-native-sortable-grid#12]
1. add onTap handler to children
2. inside onTap, change image in child
3. no update is seen

Everything behaves normally when <SortableGrid> parent is removed

**Comment by braco** [comment]
Hi @ollija, rn-sg only seems to be tracking children through `this.items` and `_saveItemOrder()`, which does not have any update mechanism. It's more of an "add unknown children" method to go along with `_removeDisappearedChildren`. 

You could include updates by altering _saveItemOrder as follows:

```
  _saveItemOrder = (items) => {
    items.forEach((item, index) => {
      const foundKey = _.findKey(this.itemOrder, oldItem => oldItem.key === item.key);
      if (foundKey) {
        this.items[foundKey] = item;
      }
      else {
        this.itemOrder.push({ key: item.key, ref: item.ref, order: this.items.length });
        if (!this.initialLayoutDone) {
          this.items.push(item);
        }
        ...
```

but IMO it would be better to stay closer to convention and order/wrap children in render with `React.children.map` and `this.props.children.sort`, or something to that effect.

**Comment by reimertz** [comment]
I have spent maybe 3 hours trying to figure out what the fux I was doing which resulted in a lot of code being refactored into better looking code trying to solve it.

But I hit a brick wall and finally realized that maybe this module doesn't update children and here we are. :D

**Comment by thomasMary** [comment]
@ollija Could you push a new version to npm please

**Comment by alex-paterson** [comment]
Yeah, this threw me off. Very necessary update.

**Comment by brycepavey** [comment]
also caught out by this, @ollija could you push an npm version?
