### ISSUE TITLE
Block width is set incorrectly

### ISSUE THREAD

**Issue by cmrichards** [ollija/react-native-sortable-grid#2]
This : 

`this.blockWidth = nativeEvent.layout.width / this.itemsPerRow`

Should be changed to this : 

`this.blockWidth = Math.floor(nativeEvent.layout.width / this.itemsPerRow)`

`If nativeEvent.layout.width / this.itemsPerRow isn't an integer (or maybe if the decimal part is greater than 0.5?), then it causes last block in the row to be rendered on the next row.   I had this problem on android.

**Comment by ollija** [comment]
Thanks!
Unfortunately I can't reproduce this (on Nexus 6 emulator), even with the decimal part of blockWidth being over 0.5. Which emulator/device are you running this on? Could you provide an example code that produces this?

**Comment by ollija** [comment]
Closing this as inactive.
