### ISSUE TITLE
Using TouchableOpacity make grid item not orderable

### ISSUE THREAD

**Issue by chhornponleu** [ollija/react-native-sortable-grid#20]
```
<SortableGrid
    itemsPerRow = { 3 }
    dragStartAnimation = {{transform: []}}
    >
    {
        ['a', 'b', 'c'].map( (letter, index) =>
            <TouchableOpacity key={index}>
                <Text>{letter}</Text>
            </TouchableOpacity>
        )
    }
</SortableGrid>
```

**Comment by shopshow** [comment]
same issue +1

**Comment by bhavukjain1** [comment]
Use `disabled`.

```sh
<SortableGrid
    itemsPerRow = { 3 }
    dragStartAnimation = {{transform: []}}
    >
    {
        ['a', 'b', 'c'].map( (letter, index) =>
            <TouchableOpacity disabled key={index}>
                <Text>{letter}</Text>
            </TouchableOpacity>
        )
    }
</SortableGrid>
```

**Comment by chhornponleu** [comment]
@bhavukjain1 
Use ```disabled ``` will not make onPress event of the TouchableOpacity be triggered.

**Comment by rajscet** [comment]
same issue

**Comment by spicyboiledfish** [comment]
same issue. I want to use the function "onPress" from TouchableOpacity, but it doesn't work to drag. And I try to use onTap from your example, it's bad, doesn't work

**Comment by stueynet** [comment]
Same here. Any other way to make the items in the grid actionable buttons?

**Comment by chhornponleu** [comment]
@stueynet I end up using another lib

**Comment by luan-nvg** [comment]
> o mesmo problema. Eu quero usar a função "onPress" do TouchableOpacity, mas não funciona para arrastar. E eu tento usar onTap do seu exemplo, é ruim, não funciona


here it worked
