### ISSUE TITLE
Different Widget Dimensions not working?

### ISSUE THREAD

**Issue by ibrahimahmed-io** [ollija/react-native-sortable-grid#9]
Hi, Love you work great stuff but i need your assistance with the dimensions of the widgets as am trying to achieve something like google keep with different dimensions for each widget however when i try to set the height and width for each widget it doesn't seem to have an effect it just displays the default dimensions i guess, Is there a way that i can set the dimensions of the widget?

**Comment by ollija** [comment]
Unfortunately no :(
